### ISSUE TITLE
XAmzContentSHA256Mismatch

### ISSUE THREAD

**Issue by marvisais** [SociallyDev/Spaces-API#10] opened 2018-07-03 15:26 UTC
Hi,

i try my best but i always get the error XAmzContentSHA256Mismatch.
I try to create a bucket with the a name i already use, and receive a 409 as expected.
So i know i can be authentifed and my setting are good.
What can cause this error: XAmzContentSHA256Mismatch?
```
Array
(
    [message] => 
    [code] => XAmzContentSHA256Mismatch
    [type] => client
    [http_code] => 400
)
```
thx

**Comment by AndreyNazarchuk** [comment] 2018-07-03 16:11
Is this what happens when you try to download?

**Comment by AndreyNazarchuk** [comment] 2018-07-03 19:05
@marvisais I need some information on how you made that error?

**Comment by marvisais** [comment] 2018-07-06 15:43
![image](https://user-images.githubusercontent.com/1869331/42387874-b9579ae6-8111-11e8-8469-22f3aef4e0a8.png)
Hi, i can do must of the action, but can create new Bucket

**Comment by SociallyDev** [comment] 2018-07-07 14:01
@marvisais It's probably related with the space name you're trying to use. 
You should read these [guidelines](http://docs.rightscale.com/faq/clouds/aws/What_are_valid_S3_bucket_names.html).


Does the error still exist when you use a name such as `spacestestsuccess`?

**Comment by marvisais** [comment] 2018-07-10 15:24
Hi, thx for the reply, sorry for the late follow up.
I do the test (spacestestsuccess), and got the same result. 
I also have a chat with DO people, and found nothing, 
I also start a new Laravel setup, and have the same result :( First try was with a long term Apiato Base app.
I this with the SociallyDev/Spaces-API package and the aws/aws-sdk-php package, always same result.

I really appreciate the help!

**Comment by SociallyDev** [comment] 2018-07-10 16:04
@marvisais If the problem still exists with AWS's official package, it's not related with Spaces-API, as Spaces-API is essentially a wrapper on top of aws-sdk-php. 
You should try raising an issue with AWS's package support team.
Just try this out first (probably not gonna work but worth a try), generate a new set of keys from the DO dashboard, and if that doesn't work, try creating a new team account, because this sounds much more like a problem on DO's end than the package's.

**Comment by marvisais** [comment] 2018-07-11 15:40
Alright I will try this out and let you know. Thx for your time.

**Comment by marvisais** [comment] 2018-07-18 16:41
Great, i will test this out!
I found my way to get a new Bucket using:
`$client = new S3Client([
            'version' => 'latest',
            'region'  => env('SPACES_REGION'),
            'endpoint' => env('SPACES_ENDPOINT'),
            'credentials' => [
                'key'    => env('SPACES_KEY'),
                'secret' => env('SPACES_SECRET'),
            ],
        ]);
        //
        try {
            $client->putObject([
                'Bucket' => $bucketName,
                'Key'    => './',
            ]);
        } catch (S3Exception $e) {
            dd($e);
        }
        echo '>>> New bucket created: '.$bucketName.PHP_EOL;`

I let you know the result of my test, thx!

**Comment by marvisais** [comment] 2018-07-18 17:05
hmmm i try, but receive the same error, did i code that correctly?
![image](https://user-images.githubusercontent.com/1869331/42896537-3b226ab0-8a8b-11e8-8c2b-48af5f0565ab.png)

Result
![image](https://user-images.githubusercontent.com/1869331/42896548-48518d06-8a8b-11e8-90ef-4d2219acb082.png)

**Comment by SociallyDev** [comment] 2018-07-20 15:16
I'm currently unable to test this, please give me a week.

**Comment by marvisais** [comment] 2018-07-21 17:31
Thx i appreciate!

**Comment by SociallyDev** [comment] 2018-07-26 15:00
@marvisais I'm unable to reproduce the error after the update, can you give me temporary keys for your Spaces? Here's my [email](devangsrivastava.github.53076c@tryninja.io).
Also, are you sure you're using the updated version? Just make sure the [signature_version line](https://github.com/SociallyDev/Spaces-API/commit/9fb77c5f2fdf6f710ce63ca8c24923086d90e6a9) is in your spaces.php file.

**Comment by SociallyDev** [comment] 2018-07-31 05:01
Closing issue since no reply received

**Closed by SociallyDev** 2018-07-31 05:01 UTC
